### ISSUE TITLE
Why not use psutil?

### ISSUE THREAD

**Issue by guettli** [al45tair/netifaces#10]
I am unsure if I should use netifaces or psutil:

  https://psutil.readthedocs.io/en/latest/#psutil.net_connections

Why should I use netifaces and not psutil?

**Comment by al45tair** [comment]
Up to you, really. netifaces is, I think, both more specialised (it only deals with network interfaces) and more general (it supports more address families), but if you already have a dependency on psutil for some other reason then you might well decide to just use that.

**Comment by guettli** [comment]
Thank you for the explanation.
