### ISSUE TITLE
 KeyError on netifaces.AF_INET

### ISSUE THREAD

**Issue by adamRogerson** [al45tair/netifaces#14]
When useing netifaces.AF_INET on a gre tunnel i get a key error. 

`*** KeyError: KeyError(2,)`

Example:
```
gre_iface = netifaces.ifaddresses("dummy_gre")

print(gre_iface) ={17: [{'broadcast': 'ff:ff:ff:ff:ff:ff', 'addr': 'b2:22:6b:2f:63:3e'}], 10: [{'netmask': 'ffff:ffff:ffff:ffff::', 'addr': `'fe80::b022:6bff:fe2f:223e%dummy_gre'}]}

print(gre_iface[netifaces.AF_INET])
*** KeyError: KeyError(2,)
```

A gre interface. 
```
1: dummy_gre@NONE: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1462 qdisc pfifo_fast master br_eth0 state UNKNOWN qlen 1000
    link/ether 12:d3:08:8e:33:d2 brd ff:ff:ff:ff:ff:ff
    inet6 fe80::10d3:8ff:fe8e:33d2/64 scope link 
       valid_lft forever preferred_lft forever
```
To create a gre tunnel/interface 
```
ip link add <name_of_iface> type gretap remote <remote_ip_of_tunnel> ttl 255 local
```

My machine 
CentOS Linux release 7.4.1708 (Core)
Linux l2lgw 3.10.0-862.2.3.el7.x86_64 #1 SMP Wed May 9 18:05:47 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

Note:
gre tunnels are have a fairly niche application so i doubt this is a priority just wanted to let people know. Nice project very handy keep up the good work.

**Comment by al45tair** [comment]
That's because there's no `AF_INET` address configured on that interface. Not really a bug — you simply need to be aware that not every interface you will encounter has an IPv4 address (or indeed an IPv6 address).
