### ISSUE TITLE
CHANGELOG doesn't describe 0.10.7

### ISSUE THREAD

**Issue by bmerry** [al45tair/netifaces#16]
The CHANGELOG only goes up to 0.10.6, but 0.10.7 has been released. What's new in 0.10.7?

**Comment by machinelearner452** [comment]
bmerry, 
 May I ask if you have been able to install 0.10.7 successfully?  I ask as I did a force reinstall and lost all functionality of this very helpful and needed package.  Thank you

**Comment by bmerry** [comment]
Seems to be working for me.

**Comment by al45tair** [comment]
This is now fixed.

**Comment by bmerry** [comment]
Thanks!
