### ISSUE TITLE
Improper mac detection?

### ISSUE THREAD

**Issue by Lvl4Sword** [al45tair/netifaces#21]
These give me proper mac addresses for the wireless card:
- ```ip link set <insert_wireless_interface_here> down```
- Being connected to a wireless network

This gives me a mac address that isn't on any of my hardware:
- Disconnecting from a wireless network ( NOT disabling wireless ) and running:
```
import netifaces

for each in netifaces.interfaces():
    try:
        print(each)
        print(netifaces.ifaddresses(each))
    except KeyError:
        pass
```

The wireless has a totally different mac address. Why?

EDIT: This is on Debian 9 and happened with the latest ( 0.10.7 ) and the apt version ( 0.10.4 )
Though both versions give a different wrong mac address ( 46:4a:22:e1:1e:01 for the 0.10.7 version, and 7e:3d:73:92:94:6e for the 0.10.4 version )

EDIT2: Output of the above command while using 0.10.7 via pip:
```
lo
{17: [{'addr': '00:00:00:00:00:00', 'peer': '00:00:00:00:00:00'}], 2: [{'netmask': '255.0.0.0', 'addr': '127.0.0.1', 'peer': '127.0.0.1'}], 10: [{'netmask': 'ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff/128', 'addr': '::1'}]}
enp7s0
{17: [{'broadcast': 'ff:ff:ff:ff:ff:ff', 'addr': '14:18:77:c7:c6:38'}]}
wlp6s0
{17: [{'broadcast': 'ff:ff:ff:ff:ff:ff', 'addr': '46:4a:22:e1:1e:01'}]}
```

**Comment by supakeen** [comment]
Many Linux distributions will randomize the mac address while scanning for new networks to anonymize your device. You can usually turn this off if you want to (but it might be a bad idea).

If you are using NetworkManager add the following to its configuration:
```
[device]
wifi.scan-rand-mac-address=no
```

Otherwise google 'do not randomize mac address wifi linux' or such.

**Comment by Lvl4Sword** [comment]
Well, my initial approach was that I was going to make a program to see if a wireless network was connected to using netifaces. Editing NetworkManager/wicd defaults could cause issues for those that don't know what they're doing.

**Comment by al45tair** [comment]
This isn't a bug; `netifaces` is returning the correct data, it's just that your operating system has a feature that causes the network card to randomise its MAC address.
