### ISSUE TITLE
Interface names under Windows

### ISSUE THREAD

**Issue by lepigocher** [al45tair/netifaces#3]
Hello,

When calling netifaces.interfaces() under Windows 10 (not tried with other versions), I receive network card ID instead of real names. Even if it's perfectly valid, it's unpracticable to show those names to commmon users in a UX.

Sample :

>>> netifaces.interfaces()
[u'{1853CD13-8E4B-4401-9FBE-D44FB27C300E}', u'{85D7707E-F178-4CCA-851B-46BD51684BBD}', u'{218AD918-B836-4E88-885C-365B94CFD14C}', u'{E9094375-5BC9-49C5-B2D9-7881522F2206}', u'{7105618B-9750-46DE-9365-47F81E0DF41B}', u'{CC8702DA-1B82-4667-9F59-BAEC57F5A8B9}', u'{8922159B-67D7-4597-A1C2-DAF4320B20A6}', u'{FFD7E77E-DF65-11E7-9888-806E6F6E6963}']

**Comment by al45tair** [comment]
This is definitely not a bug. IIRC on Windows, if you install two network adapters of the same type, the display names are not helpful anyway.

And, frankly, even on UNIX systems, the names aren't that useful. I mean, sure, developers and sysadmins might know that "eth0" (for instance) was the first Ethernet socket and that "eth1" was (perhaps) WiFi, but end users can't reasonably be expected to know that.

There *might* be a case for adding a way to retrieve some kind of human-friendly name to netifaces, mind.

**Comment by ephraim** [comment]
I had the same 'Ahemmm, What?!' moment when looking at the windows interface names.

For those who are interessted in the friendly names. Here is a patch which uses the human friendly names of the adapters.

[patch.txt](https://github.com/al45tair/netifaces/files/4387980/patch.txt)

Cheers
Thilo

**Comment by al45tair** [comment]
@ephraim The problem with that is that those names aren't guaranteed to stay the same. Maybe there's a case for having a separate friendly name as well as the unique interface name?

**Comment by ephraim** [comment]
Guaranteed to stay the same? In which timeframe. I just need it to stay the same from one execution of my pythonscript to show the interface names and another execution with one choosen.
Thats my usecase ... For that my change is enough. It's definitely not the very solution but it's a workaround until a good solution is available.
Perhaps having both (on windows) the friendly name and the adapter name in the interfaces dictionary ... or have an extra entry friendlyname which is optional .... 
or something like that

**Comment by al45tair** [comment]
Some people using netifaces need to be able to save interface names in a file and then their software can load them later on. That's why I say, I think maybe the right solution here is to add a user-visible name (not just on Windows either; the entire point is that this module has to work in an equivalent manner everywhere). macOS also has user-friendly names, so maybe if I can work out how I'll be able to add them too.

**Comment by ephraim** [comment]
Yeah would be great. I understand, that in a configuartion file or regkey, there need to be a stable name for the interface. But for a case where a user needs to choose, is a friendly name much better.
IMHO, under linux with networkmanager, you have the connection which configures the real network device. That connection's name is mostly more userfriendly than the interface name itself. 
So this might be a solution for friendly names under linux.
Anyway, friendly names should be optional and the adapter name, in case of Windows the GUID, is the way to save it. I totaly agree with you in that!
