### ISSUE TITLE
Build failure but successful installation on Windows 10 with python 2.7 on 0.10.8

### ISSUE THREAD

**Issue by XnorTheDestroyer** [al45tair/netifaces#30]
I noticed a weird issue with the netifaces installation on Windows. The build fails but somehow the module still get installed. So far it seems to be working after installation but I'm not using all the module's features, so I'm not sure if anything is broken. The problem does not happen with netifaces 0.10.7, only 0.10.8

**Environnement:**
Repeated on multiple Windows 10 machines. Issue does not happen on Linux.
Latest python 2.7.15 installed
VCForPython27.msi installed

**Steps to reproduce:**
1. Create a python virtual environment with python 2.7:
_virtualenv -p C:\python27\python.exe .pyenv_
2. Activate the python virtual environment:
_.pyenv\Scripts\activate_
3. Install netifaces latest version:
_pip install netifaces==0.10.8_

**Actual Result:**
Gives weird build failure error but installs successfully:
```
Looking in indexes: https://packagemanager.octasic.com/octasic/current/+simple/
Collecting netifaces==0.10.8
  Downloading https://packagemanager.octasic.com/octasic/pypi/+f/bef/c9800751991c0/netifaces-0.10.8.tar.gz
Building wheels for collected packages: netifaces
  Running setup.py bdist_wheel for netifaces ... error
  Complete output from command d:\scripts\test_stuff\.pyenv\scripts\python.exe -u -c "import setuptools, tokenize;__file__='c:\\users\\xamer\\appdata\\local\\temp\\pip-install-dlcwj0\\netifaces\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d c:\users\xamer\appdata\local\temp\pip-wheel-ndovly --python-tag cp27:
  running bdist_wheel
  running build
  running build_ext
  building 'netifaces' extension
  creating build
  creating build\temp.win-amd64-2.7
  creating build\temp.win-amd64-2.7\Release
  C:\Users\xamer\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\amd64\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -DWIN32=1 -DNETIFACES_VERSION=0.10.8 -IC:\python27\include -Id:\scripts\test_stuff\.pyenv\PC /Tcnetifaces.c /Fobuild\temp.win-amd64-2.7\Release\netifaces.obj
  netifaces.c
  creating build\lib.win-amd64-2.7
  C:\Users\xamer\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\amd64\link.exe /DLL /nologo /INCREMENTAL:NO /LIBPATH:C:\python27\Libs /LIBPATH:d:\scripts\test_stuff\.pyenv\libs /LIBPATH:d:\scripts\test_stuff\.pyenv\PCbuild\amd64 /LIBPATH:d:\scripts\test_stuff\.pyenv\PC\VS9.0\amd64 ws2_32.lib iphlpapi.lib /EXPORT:initnetifaces build\temp.win-amd64-2.7\Release\netifaces.obj /OUT:build\lib.win-amd64-2.7\netifaces.pyd /IMPLIB:build\temp.win-amd64-2.7\Release\netifaces.lib /MANIFESTFILE:build\temp.win-amd64-2.7\Release\netifaces.pyd.manifest
     Creating library build\temp.win-amd64-2.7\Release\netifaces.lib and object build\temp.win-amd64-2.7\Release\netifaces.exp
  installing to build\bdist.win-amd64\wheel
  running install
  running install_lib
  creating build\bdist.win-amd64
  creating build\bdist.win-amd64\wheel
  copying build\lib.win-amd64-2.7\netifaces.pyd -> build\bdist.win-amd64\wheel\.
  running install_egg_info
  running egg_info
  writing netifaces.egg-info\PKG-INFO
  writing top-level names to netifaces.egg-info\top_level.txt
  writing dependency_links to netifaces.egg-info\dependency_links.txt
  reading manifest file 'netifaces.egg-info\SOURCES.txt'
  writing manifest file 'netifaces.egg-info\SOURCES.txt'
  Copying netifaces.egg-info to build\bdist.win-amd64\wheel\.\netifaces-0.10.8-py2.7.egg-info
  running install_scripts
  d:\scripts\test_stuff\.pyenv\lib\site-packages\wheel\pep425tags.py:80: RuntimeWarning: Config variable 'Py_DEBUG' is unset, Python ABI tag may be incorrect
    warn=(impl == 'cp')):
  d:\scripts\test_stuff\.pyenv\lib\site-packages\wheel\pep425tags.py:84: RuntimeWarning: Config variable 'WITH_PYMALLOC' is unset, Python ABI tag may be incorrect
    warn=(impl == 'cp')):
  d:\scripts\test_stuff\.pyenv\lib\site-packages\wheel\pep425tags.py:90: RuntimeWarning: Config variable 'Py_UNICODE_SIZE' is unset, Python ABI tag may be incorrect
    sys.version_info < (3, 3))) \
  error: [Errno 2] No such file or directory: 'LICENSE'

  ----------------------------------------
  Failed building wheel for netifaces
  Running setup.py clean for netifaces
Failed to build netifaces
Installing collected packages: netifaces
  Running setup.py install for netifaces ... done
Successfully installed netifaces-0.10.8
```

**Expected Result:**
If the build fails it should not install afterwards. Possibly output a clear error message on what to do if build fails.

Let me know if you need more info for troubleshooting.

**Comment by pabelanger** [comment]
https://github.com/al45tair/netifaces/pull/31 fixes the issue for me, but I am not familiar enough with python packaging to understand why this is needed.

**Comment by pabelanger** [comment]
Basically, the LICENSE file is missing from the tarball uploaded to pypi

**Comment by al45tair** [comment]
Yep, sorry about this. I'll be releasing 0.10.9 to fix it (the only change being adding LICENSE to MANIFEST.in — thanks Paul).

**Comment by al45tair** [comment]
OK, should be fixed now. Thanks again, @pabelanger.

**Comment by trojan-TR0J4N** [comment]
AL INTENTAR INSTALAR NETIFACES APARECE EL SIGUIENTE ERROR


ERROR: Command errored out with exit status 1:
   command: 'c:\users\david\appdata\local\programs\python\python38-32\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\DAVID\\AppData\\Local\\Temp\\pip-install-apfxyfk4\\netifaces\\setup.py'"'"'; __file__='"'"'C:\\Users\\DAVID\\AppData\\Local\\Temp\\pip-install-apfxyfk4\\netifaces\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\DAVID\AppData\Local\Temp\pip-wheel-uuvnp6rw'
       cwd: C:\Users\DAVID\AppData\Local\Temp\pip-install-apfxyfk4\netifaces\
  Complete output (11 lines):
  running bdist_wheel
  running build
  running build_ext
  building 'netifaces' extension
  creating build
  creating build\temp.win32-3.8
  creating build\temp.win32-3.8\Release
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -DWIN32=1 -DNETIFACES_VERSION=0.10.9 -Ic:\users\david\appdata\local\programs\python\python38-32\include -Ic:\users\david\appdata\local\programs\python\python38-32\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" /Tcnetifaces.c /Fobuild\temp.win32-3.8\Release\netifaces.obj
  netifaces.c
  c:\users\david\appdata\local\programs\python\python38-32\include\pyconfig.h(206): fatal error C1083: No se puede abrir el archivo incluir: 'basetsd.h': No such file or directory
  error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\cl.exe' failed with exit status 2
  ----------------------------------------
  ERROR: Failed building wheel for netifaces
  Running setup.py clean for netifaces
Failed to build netifaces
DEPRECATION: Could not build wheels for netifaces which do not use PEP 517. pip will fall back to legacy 'setup.py install' for these. pip 21.0 will remove support for this functionality. A possible replacement is to fix the wheel build issue reported above. You can find discussion regarding this at https://github.com/pypa/pip/issues/8368.
Installing collected packages: netifaces
    Running setup.py install for netifaces ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\david\appdata\local\programs\python\python38-32\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\DAVID\\AppData\\Local\\Temp\\pip-install-apfxyfk4\\netifaces\\setup.py'"'"'; __file__='"'"'C:\\Users\\DAVID\\AppData\\Local\\Temp\\pip-install-apfxyfk4\\netifaces\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\DAVID\AppData\Local\Temp\pip-record-viyq8oa2\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\david\appdata\local\programs\python\python38-32\Include\netifaces'
         cwd: C:\Users\DAVID\AppData\Local\Temp\pip-install-apfxyfk4\netifaces\
    Complete output (11 lines):
    running install
    running build
    running build_ext
    building 'netifaces' extension
    creating build
    creating build\temp.win32-3.8
    creating build\temp.win32-3.8\Release
    C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -DWIN32=1 -DNETIFACES_VERSION=0.10.9 -Ic:\users\david\appdata\local\programs\python\python38-32\include -Ic:\users\david\appdata\local\programs\python\python38-32\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" /Tcnetifaces.c /Fobuild\temp.win32-3.8\Release\netifaces.obj
    netifaces.c
    c:\users\david\appdata\local\programs\python\python38-32\include\pyconfig.h(206): fatal error C1083: No se puede abrir el archivo incluir: 'basetsd.h': No such file or directory
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\cl.exe' failed with exit status 2
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\david\appdata\local\programs\python\python38-32\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\DAVID\\AppData\\Local\\Temp\\pip-install-apfxyfk4\\netifaces\\setup.py'"'"'; __file__='"'"'C:\\Users\\DAVID\\AppData\\Local\\Temp\\pip-install-apfxyfk4\\netifaces\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\DAVID\AppData\Local\Temp\pip-record-viyq8oa2\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\david\appdata\local\programs\python\python38-32\Include\netifaces' Check the logs for full command output.

**Comment by lioobayoyo** [comment]
problem for me was that I was blindly following some tutorials, but since I was using python3

* I hadn't install ed the proper dev tools:

```
sudo apt-get install build-essential libssl-dev libffi-dev python3-dev
```

note the `python3-dev` instead of `python-dev`.

And also, I forgot to install `wheel` beforehand

```
sudo apt-get install wheel
```
