### ISSUE TITLE
how to find linux-mips-2.7/netifaces.o

### ISSUE THREAD

**Issue by novski** [al45tair/netifaces#37]
I'm not experienced with python and try to install webthing from mozilla on a IoT device, thats why im asking for such strange arch support. 
Is there any way to find a older or even any MIPS architecture compliled version?

**Comment by al45tair** [comment]
You'll need to build it yourself, either using an appropriately configured MIPS cross-compiler, or by installing the relevant developer tools on the MIPS system and then running `python setup.py install` from there.

**Comment by novski** [comment]
are this developer tools python specific or processor specific? 
-> can you link me to the developertools?
