### ISSUE TITLE
netifaces.c:210:6: error: #error You need to add code for your platform.

### ISSUE THREAD

**Issue by hennes131** [al45tair/netifaces#43]
Hi,
trying to install from 10.09.tar offline on AWS EC2 instance with RHEL 7.6.5 and cannot get it installed. Could you give me a hint where to debug this?

Further error is:

 #    error You need to add code for your platform.
      ^
netifaces.c: In function ‘gateways’:
netifaces.c:1466:22: warning: unused variable ‘defaults’ [-Wunused-variable]
   PyObject *result, *defaults;
                      ^
netifaces.c: At top level:
netifaces.c:438:1: warning: ‘string_from_netmask’ defined but not used [-Wunused-function]
 string_from_netmask (struct sockaddr *addr,
 ^
netifaces.c:689:1: warning: ‘add_to_family’ defined but not used [-Wunused-function]
 add_to_family (PyObject *result, int family, PyObject *obj)
 ^
error: command 'gcc' failed with exit status 1

Thanks in advance

**Comment by NitinJamadagni** [comment]
+1

**Comment by NIL-zhuang** [comment]
So do manjaro

**Comment by al45tair** [comment]
That error likely means that you don't have the development header files installed on your system. In that case, netifaces will be unable to find any way to obtain the information it's supposed to give you.

Installing the developer tools differs between different platforms (even between different Linux distributions). For RHEL, Centos or Amazon Linux:

    yum update && yum groupinstall "Development Tools"

For Fedora:

    dnf update && dnf groupinstall "Development Tools"

For Debian or Ubuntu:

    apt update && apt install build-essential

Netifaces does have wheels that work for some platforms, which obviates the need for the developer tools, but if you aren't on one of those, you need a compiler and system headers installed or it won't work.
