### ISSUE TITLE
Wrong netmask for IPv6 address

### ISSUE THREAD

**Issue by harshalbarefoot** [al45tair/netifaces#45]
Check netmask (67) displayed by ifconfig (which is right) and netmask (65) displayed by netifaces:

myterminal:~$ /sbin/ifconfig PortChannel1111
PortChannel1111: flags=4099<UP,BROADCAST,MULTICAST>  mtu 9100
        inet6 2001::1  prefixlen 64  scopeid 0x0<global>
        inet6 2001::2  prefixlen 65  scopeid 0x0<global>
        inet6 **2001::3  prefixlen 67**  scopeid 0x0<global>  <-- ifconfig has correct value
        ether 00:90:fb:5e:d6:ba  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

myterminal:~$ python
Python 2.7.13 (default, Sep 26 2018, 18:42:22) 
[GCC 6.3.0 20170516] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import netifaces
>>> netifaces.ifaddresses('PortChannel1111') 
{17: [{'broadcast': u'ff:ff:ff:ff:ff:ff', 'addr': u'00:90:fb:5e:d6:ba'}], 10: [{'netmask': u'**ffff:ffff:ffff:ffff:e000::/65', 'addr': u'2001::3'**}, {'netmask': u'ffff:ffff:ffff:ffff:8000::/65', 'addr': u'2001::2'}, {'netmask': u'ffff:ffff:ffff:ffff::/64', 'addr': u'2001::1'}]}
>>>

**Comment by al45tair** [comment]
Fixed by your pull request. Thank-you.
