### ISSUE TITLE
linux　Build and compile errors during installation and execution

### ISSUE THREAD

**Issue by WangSongsen** [al45tair/netifaces#60]
![image](https://user-images.githubusercontent.com/66193944/89759308-61b17680-dad9-11ea-9f2a-0832ae963471.png)
　Wrote a test file to understand the library　but I seem to have some trouble and don't know how to solve it

![image](https://user-images.githubusercontent.com/66193944/89759451-c240b380-dad9-11ea-83eb-502944600599.png)

**Comment by al45tair** [comment]
This is nothing to do with netifaces.  You're presumably after [psutil](https://github.com/giampaolo/psutil)?

**Comment by WangSongsen** [comment]
so sorry 
Why the test case (test.py) in our library cannot be executed（linux　python3.7）
![image](https://user-images.githubusercontent.com/66193944/89760834-b0144480-dadc-11ea-8507-469a6ae2a14a.png)

**Comment by al45tair** [comment]
If I had to guess, it's because you've got something in `sys.path` (i.e. `PYTHONPATH`) that is called `netifaces` but that isn't actually netifaces. If there's an `__init__.py` in the directory this test program is in, it could even be this directory itself.
